STATICPROCNAME ?= libbkkms.a

SRC_DIR += $(CURDIR)/types/
SRC_DIR += $(CURDIR)/internal/common/
SRC_DIR += $(CURDIR)/internal/crypto/
SRC_DIR += $(CURDIR)/internal/crypto/rsa/
SRC_DIR += $(CURDIR)/internal/crypto/sm2/
SRC_DIR += $(CURDIR)/internal/crypto/aes/
SRC_DIR += $(CURDIR)/internal/crypto/sm4/
SRC_DIR += $(CURDIR)/internal/signature/
SRC_DIR += $(CURDIR)/consume/

include ../scripts/Makefile
