<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ TencentBlueKing is pleased to support the open source community by making
  ~ 蓝鲸智云 - 凭证管理服务(BlueKing - Key Management Service) available.
  ~ Copyright (C) 2022 THL A29 Limited, a Tencent company. All rights reserved.
  ~ Licensed under the MIT License (the "License"); you may not use this file except
  ~ in compliance with the License. You may obtain a copy of the License at
  ~ http://opensource.org/licenses/MIT
  ~ Unless required by applicable law or agreed to in writing, software distributed
  ~ under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
  ~ CONDITIONS OF ANY KIND, either express or implied. See the License for the specific
  ~ language governing permissions and limitations under the License.We undertake not
  ~ to change the open source license (MIT license) applicable to the current version
  ~ of the project delivered to anyone in the future.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tencent.bk.kms.examples</groupId>
    <artifactId>consume-envelope-example</artifactId>
    <version>1.0.0-alpha.1</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.tencent.bk.kms</groupId>
            <artifactId>kms-core-sdk</artifactId>
            <version>1.0.0-alpha.1</version>
        </dependency>
    </dependencies>
</project>
